### ISSUE TITLE
Soundness hole in mutable HKT thread-local: Sufficiently general `ReborrowMut` implementation is not properly enforced.

### ISSUE THREAD

**Issue by steffahn** [Diggsey/scoped-tls-hkt#3]
```rs
use scoped_tls_hkt::{scoped_thread_local, ReborrowMut};
use std::sync::OnceLock;

static STR_HOLDER: OnceLock<&str> = OnceLock::new();
struct S<'a>(&'a str);
impl<'a> ReborrowMut<'a> for S<'static> {
    type Result = S<'a>;

    fn reborrow_mut(&'a mut self) -> Self::Result {
        STR_HOLDER.set(self.0).unwrap();
        S("")
    }
}

fn main() {
    scoped_thread_local!(static mut STRING: for<'a> S<'a>);
    let string = String::from("Hello World");
    STRING.set(S(&string), || STRING.with(|_| ()));

    let hello: &str = STR_HOLDER.get().unwrap();
    println!("now it exists: {hello}");
    drop(string);
    println!("now it's gone: {hello}");
}
```
```plain
now it exists: Hello World
now it's gone: >�e�3~
```

---

The relevant code is
```rs
// This wrapper helps to ensure that the 'static lifetime is not visible
// to the safe code.
fn cast_from_static<'a, 'b>(x: &'a mut Hkt<'static>) -> Hkt<'b> where 'a: 'b {
    ReborrowMut::reborrow_mut(x)
}
```

This only enforces a `ReborrowMut` implementation to be present for `Hkt<'static>`.
It thus does ***not*** do as promised, and it *does* expose the `'static` lifetime to safe user code.

Probably can be fixed by making `cast_from_static` more generic… a change like this might be sufficient (though I haven’t tested it):
```rs
// This wrapper helps to ensure that the 'static lifetime is not visible
// to the safe code.
fn cast_from_static<'a, 'b>(x: &'a mut Hkt<'_>) -> Hkt<'b> where 'a: 'b {
    ReborrowMut::reborrow_mut(x)
}
```

_Edit:_ I’ve tested it now, this change should be sufficient.

**Comment by Diggsey** [comment]
Thanks for the report. I believe the change you suggested doesn't quite work as the surrounding code requires  `Hkt<'static>` to be passed as the argument to `cast_from_static`, or else it will fail to compile for valid uses.

However, it is simple enough to cast the lifetime to `'a` before calling `reborrow_mut()`, thus ensuring that user code never sees the `'static` lifetime. This fix is published in 0.1.3.

**Comment by steffahn** [comment]
No, your fix isn’t sufficient. I also don’t quite understand your issue with the fix I suggested. What use cases will fail to compile?

The `&'a mut Hkt<'a>` case, too, is *not* sufficiently general, and trait implementations of `ReborrowMut` restricted to that case alone can result in UB as well. This time it doesn’t offer the user code a fake `'static`, but it does offer the false information that `Hkt<'a>` would be borrowed, essentially, for its entire duration of existence, allowing user code to do “fun” (and entirely unsound) self-referential stuff with it:
```rs
use scoped_tls_hkt::{scoped_thread_local, ReborrowMut};

struct S<'a>(&'a mut String, Option<&'a mut String>);
impl<'a> ReborrowMut<'a> for S<'a> {
    type Result = S<'a>;

    fn reborrow_mut(&'a mut self) -> Self::Result {
        if self.1.is_none() {
            self.1 = Some(self.0);
            S(Box::leak(Box::new(String::new())), None)
        } else {
            S(self.0, self.1.as_deref_mut())
        }
    }
}

fn main() {
    scoped_thread_local!(static mut STRING: for<'a> S<'a>);
    let mut string = String::from("Hello World");
    STRING.set(S(&mut string, None), || {
        STRING.with(|_| ()); // this first call writes a “copy” of the mutable
                             // reference into the second field
        STRING.with(|mut s| {
            let hello: &str = s.0;
            println!("now it exists: {hello}");
            drop(std::mem::take(s.1.as_deref_mut().unwrap()));
            println!("now it's gone: {hello}");
        });
    });
}
```

**Comment by steffahn** [comment]
For the record, the “correct” signature for a re-borrow signature should be “`&'b mut Hkt<'a> -> Hkt<'b>`”. Anything that doesn’t properly ensure that this conversion is supported (for all lifetimes `'b, 'a: 'b`) is probably unsound.

**Comment by steffahn** [comment]
I’d appreciate if the issue is re-opened 🙂  – also, if you want to save on version numbers, I’ll gladly review any fix before it’s published to crates.io 😉

**Comment by Diggsey** [comment]
> No, your fix isn’t sufficient. I also don’t quite understand your issue with the fix I suggested. What use cases will fail to compile?

This was my mistake, I changed the soundness example you provided to make it actually sound to check that the solution didn't break the sound use-case and got the following error from inside the macro definition:

> explicit lifetime required in the type of `x`
lifetime `'a` required

I mistook this to mean that the signature of the function with the implicit lifetime was a problem, but it turns out the error message is just misleading, and I'd missed a lifetime whilst "fixing" the unsound ReborrowMut implementation.

I've pushed the fix you suggested, although I would like to give a better error message if the ReborrowMut implementation is incorrect. Now that GATs are stable, this should probably be rewritten to use that feature which might give better error messages...

**Comment by steffahn** [comment]
I know, the error message is pretty bad. I had tried a few approaches to make it better, but haven’t succeeded without starting to break valid test cases.

The compiler seems to love to find the “matching” trait implementation, and give rise to lifetime errors afterwards which never mention the “`ReborrowMut`” trait again. And a `for<'a, 'b> ReborrowMut<'b> for Hkt<'a>` requirement doesn’t play nice with any implementation that was restricted to the `'a: 'b` case, such as the ones for references.

**Comment by steffahn** [comment]
Maybe a creatively named lifetime, and some tweak that makes the error message at least a little shorter:
```rs

                // This wrapper helps to ensure that the 'static lifetime is not visible
                // to the safe code.
                fn cast_from_static<'is_reborrow_mut_general_enough_test, 'a, 'b>(x: &'a mut Hkt<'is_reborrow_mut_general_enough_test>) -> Hkt<'b> where 'a: 'b {
                    <Hkt<'is_reborrow_mut_general_enough_test> as ReborrowMut<'_>>::reborrow_mut(x)
                }
```

Error for test-case involving `'static`
![Screenshot_20230814_030901](https://github.com/Diggsey/scoped-tls-hkt/assets/3986214/a4637df8-e1ea-4273-9634-b733807ca19e)
Error for test-case only implementing `ReborrowMut<'a>` for `Hkt<'a>`
![Screenshot_20230814_031030](https://github.com/Diggsey/scoped-tls-hkt/assets/3986214/ff68ad09-b443-421f-8358-4a22b0af1d6e)

---

_Edit:_ Another creative name could be:
```rs
               // This wrapper helps to ensure that the 'static lifetime is not visible
                // to the safe code.
                #[allow(non_snake_case)]
                fn cast_from_static<'implementation_of_ReborrowMut_may_not_be_general_enough, 'a, 'b>(x: &'a mut Hkt<'implementation_of_ReborrowMut_may_not_be_general_enough>) -> Hkt<'b> where 'a: 'b {
                    <Hkt<'implementation_of_ReborrowMut_may_not_be_general_enough> as ReborrowMut<'_>>::reborrow_mut(x)
                }
```
```
error: lifetime may not live long enough
  --> src/main.rs:16:5
   |
16 |     scoped_thread_local!(static mut STRING: for<'a> S<'a>);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     lifetime `'implementation_of_ReborrowMut_may_not_be_general_enough` defined here
   |     requires that `'implementation_of_ReborrowMut_may_not_be_general_enough` must outlive `'static`
   |
   = note: this error originates in the macro `scoped_thread_local` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by Diggsey** [comment]
Thanks, this is now released 👍
