### ISSUE TITLE
Please make a new release on crate.io to fix non_local_definitions warning

### ISSUE THREAD

**Issue by ogoffart** [Diggsey/scoped-tls-hkt#5]
The non_local_definitions lint is back to warn by default in rust nightly: https://github.com/rust-lang/rust/pull/127015
There was a fix in https://github.com/Diggsey/scoped-tls-hkt/pull/4 , but it hasn't been released yet to crates.io
(The warning occurs at the usage site when compiling our crate, not when compiling scoped-tls-hkt)

A release on crates.io would be appreciated.

Edit: link to rust PR was meant to be https://github.com/rust-lang/rust/pull/127117

**Comment by Diggsey** [comment]
This is now released 👍
